### ISSUE TITLE
Move automl samples to googleapis/nodejs-automl

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-translate#200]
We have `automl` samples sitting in this repo.  While they're samples about translation, they're unrelated to this npm module.  We should move these samples over to googleapis/nodejs-automl, so that they're tested as part of the release process of that module.

**Comment by beccasaurus** [comment]
Hey @nirupa-kumar! Do you have availability to move the AutoML samples into the nodejs-automl repository?

Essentially: `mv googleapis/nodejs-translate/samples/automl googleapis/nodejs-automl/samples/tramslate`

I'm filing the sample issue for nodejs-vision (to move samples from vision --> automl)

**Comment by callmehiphop** [comment]
\o @JustinBeckwith I noticed automl uses the new samples format, so I'm guessing this isn't just a copy/paste. Is there any documentation on said format, or should I just try and follow by example and seek feedback?

**Comment by beccasaurus** [comment]
No opinion from ML APIs. I would wait for these to be gen'd rather than put capacity into refactoring. But I do not have a timeframe commitment beyond "in the next few months" for that. Justin can speak to the priority of this for his team.

**Comment by beccasaurus** [comment]
Reminder: do not delete this until you've published docs from the new location on nodejs-automl 😉

**Comment by munkhuushmgl** [comment]
small update, I just got started on this.
