### ISSUE TITLE
Synth generation is broken

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-translate#379]
The synth changes in here are causing TypeScript compilation errors:
https://github.com/googleapis/nodejs-translate/pull/377

Not sure what's causing it :(

**Comment by alexander-fenster** [comment]
This one is a weird oddball right now since it's half JS, half TS.  It's on my list to be converted to TS right after the text-to-speech is done.

**Comment by alexander-fenster** [comment]
What I mean is - no need to spend time fixing JS+TS mix since it will go away soon.

**Comment by bcoe** [comment]
see: https://github.com/googleapis/nodejs-translate/pull/377 we just need ot update `synth.py` mainly.
