### ISSUE TITLE
TypeScript types for @google-cloud/translate

### ISSUE THREAD

**Issue by IchordeDionysos** [googleapis/nodejs-translate#38]
Would be great if there were types for `@google-cloud/translate` as there is `@types/google-cloud__storage`.

**Comment by stephenplusplus** [comment]
We have this issue that's tracking our widespread support for TypeScript: https://github.com/googlecloudplatform/google-cloud-node/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc. Please subscribe-- this is an ongoing effort :)
