### ISSUE TITLE
Demo: use access_token instead of service account

### ISSUE THREAD

**Issue by 1c7** [googleapis/nodejs-translate#397]
![image](https://user-images.githubusercontent.com/1804755/69958944-e4446800-1540-11ea-8280-71d3d1afcff6.png)
# Image above is the only example

# Please add one more example
Demo how to use access_token for Google Translate API
(access_token come from OAuth, I already got this part done, I am translate on users behalf. so the app cost user money instead of mine)

(I am building an Electron desktop app that use Google Translate. the OAuth part is done. now I just need to know what to do with the access_token)

Thank you

**Comment by stephenplusplus** [comment]
Hello! Unfortunately, the authentication library we are using does not support passing an `access_token` directly. We have an issue tracking that feature request here: https://github.com/googleapis/google-auth-library-nodejs/issues/677. Please subscribe to that issue for updates.

**Comment by 1c7** [comment]
@stephenplusplus  Thanks 😄

**Comment by 1c7** [comment]
By the way, For other people who also got the same problem.
if you want to use OAuth access_token for Google Translate API.
For now, You can just send HTTP request in this format:

![image](https://user-images.githubusercontent.com/1804755/69960775-4f903900-1545-11ea-9263-a6f838ed432d.png)
This screenshot come from this document:
https://cloud.google.com/translate/docs/basic/setup-basic
