### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: The request is missing a valid API key.

### ISSUE THREAD

**Issue by sutriptaroy** [googleapis/nodejs-translate#421]
Though I'm providing correct project id, it is saying invalid api key

**Comment by bcoe** [comment]
@sutriptaroy what environment are you running `@google-cloud/translate` in? and would you be able to provide some sample code for how you're initializing the client?

**Comment by JustinBeckwith** [comment]
Greetings!  If this is still an issue, and you can provide some sample code - please do let us know!
