### ISSUE TITLE
Test and lint errors when following Contributing Guide

### ISSUE THREAD

**Issue by texasmichelle** [googleapis/nodejs-translate#423]
#### Environment details

  - OS: Debian GNU/Linux 9 (stretch)
  - Node.js version: v13.6.0
  - npm version: 6.13.4
  - `@google-cloud/translate` version: 5.1.4

#### Steps to reproduce

1.   On a fresh debian-9-drawfork-v20191004 instance, follow the instructions in CONTRIBUTING.md to setup the environment (use the linked GCP documentation, then run `npm install` in the root of this repo).
2.  Run tests as described in the guide and receive errors about missing packages.
3.  Run linter and receive errors.

**Comment by JustinBeckwith** [comment]
Pretty sure this was addressed with recent changes to the `prelint` script used across the board :)
