### ISSUE TITLE
getting client_email missing even though I am passing projectId in nodeJs

### ISSUE THREAD

**Issue by mamta-dhaka** [googleapis/nodejs-translate#477]
The incoming JSON object does not contain a client_email field
    at JWT.fromJSON (/node_modules/google-auth-library/build/src/auth/jwtclient.js:193:19)
    at GoogleAuth._cacheClientFromJSON (/node_modules/google-auth-library/build/src/auth/googleauth.js:313:16)
    at ReadStream.inputStream.setEncoding.on.on.on (/node_modules/google-auth-library/build/src/auth/googleauth.js:347:36)

**Comment by bcoe** [comment]
👋 could I bother you to provide some code demonstrating what you're trying to do, I'm not 100% sure following where you're expecting the email field to be populated.

**Comment by mamta-dhaka** [comment]
code snippet: 
const { Translate } = require('@google-cloud/translate').v2;

const translate = new Translate({ projectId });

const text = 'Hello, world!';

        // The target language
        const target = 'hi-IN';
        const [translation] = await translate.translate(text, target);

**Comment by bcoe** [comment]
@mamta-dhaka could you please:

```
rm -rf node_modules
rm package-lock.json
npm i
```

And try running the program again, I just want to make sure you're not being bitten by an issue we had with a dependent library recently.

**Comment by mamta-dhaka** [comment]
okay, i followed above steps, still same error I got, tried giving the whole config in contructor like
const translate = new Translate({ keyFilename: 'config.default.json' });
after this I am getting
{ Error: Invalid Value
    at new ApiError (/Users/apple/Desktop/node_modules/@google-cloud/common/build/src/util.js:58:15)
    at Util.parseHttpRespBody (/Users/apple/Desktop/node_modules/@google-cloud/common/build/src/util.js:193:38)
    at Util.handleResp (/Users/apple/Desktop/node_modules/@google-cloud/common/build/src/util.js:134:117)
    at retryRequest (/Users/apple/Desktop/node_modules/@google-cloud/common/build/src/util.js:432:22)
    at onResponse (/Users/apple/Desktop/node_modules/retry-request/index.js:206:7)
    at /Users/apple/Desktop/node_modules/teeny-request/build/src/index.js:233:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 400,
  errors:
   [ { message: 'Invalid Value', domain: 'global', reason: 'invalid' } ],

**Comment by bcoe** [comment]
@mamta-dhaka rather than passing the `config.default.json`, could you create service account credentials that specifically grant translate permissions, following the steps outlined here:

https://cloud.google.com/docs/authentication/getting-started

Rather than setting `{ keyFilename: 'config.default.json' }`, you would then simply set the environment variable: `GOOGLE_APPLICATION_CREDENTIALS`.

**Comment by mamta-dhaka** [comment]
yes @bcoe, thanks for the suggestion, i have created a service account, and set node env var, 
tried logging also inside /Users/apple/Desktop/x/node_modules/google-auth-library/build/src/auth/googleauth.js, line 186
console.log('>>>>>', process.env['GOOGLE_APPLICATION_CREDENTIALS'])
>>>>> /Users/apple/Downloads/testProject-db61361e46dc.json

env got set, still getting the same error.

**Comment by bcoe** [comment]
@mamta-dhaka 👋 could you please share the script, as you're running it now? I would expect the following:

```js
const { Translate } = require('@google-cloud/translate').v2;
const translate = new Translate();

async run () {
    const text = 'Hello, world!';
    const target = 'hi-IN';
    const [translation] = await translate.translate(text, target);
}

run();
```

You would then run:

```
GCLOUD_PROJECT=my-project-name GOOGLE_APPLICATION_CREDENTIALS=/Users/apple/Downloads/testProject-db61361e46dc.json node my-program.js
```

Where `my-project-name` is replaced with the project you have downloaded the credentials from.

If you're continuing to have issues, I recommend starting with the [quickstart sample](https://github.com/googleapis/nodejs-translate/blob/master/samples/quickstart.js), which I just confirmed is working as expected.

**Comment by mamta-dhaka** [comment]
yes @bcoe , thanks for sharing the example, i am following the exact same set of steps but getting 400 (message: 'Invalid Value', statusMessage: 'Bad Request'). looks like an ApiError.

**Comment by nnegrey** [comment]
Howdy, just to check a few things. 
Looks like you are currently using the v2 version of translate (basic) vs. v3 (advanced). 
Setup for that is here: https://cloud.google.com/translate/docs/basic/setup-basic

Then here is this page for translating text: https://cloud.google.com/translate/docs/simple-translate-call#translate_translate_text-nodejs

Though, from the error messages sounds like something is mis-configured on your machine.

**Comment by mamta-dhaka** [comment]
@nnegrey @bcoe thank you for the help, now I am able to send request,
'Invalid Value' was coming because i was sending wrong language code (may be a better error code might have helped here). also i thought language code has to be picked from https://cloud.google.com/speech-to-text/docs/languages instead of iso-codes.
anyway thanks for the help.
