### ISSUE TITLE
Error when install on Mac OS Mojave

### ISSUE THREAD

**Issue by quangdv90** [googleapis/nodejs-translate#550]
When i install @google-cloud/translate on mac os. I received an error:
npm ERR! Unexpected end of JSON input while parsing near '...0","linkinator":"^1.1'
- Mac OS mojave: 10.14.6
- nodejs v12.18.0
- npm 6.14.4
pls, let me known how to fix it?

**Comment by stephenplusplus** [comment]
Hi @quangdv90! Could you paste your package.json in here? I can't tell where the issue is, but it looks like there's a malformed JSON file somewhere. You could also try removing the "node_modules" directory in your project and running "npm install" again.

**Comment by quangdv90** [comment]
This is my package.json
{
    "name": "alimuaha",
    "repository": {
        "type": "git",
        "url": "git+https://github.com/ducdhm/alimuaha-web.git"
    },
    "keywords": [
        "mongodb",
        "expressjs",
        "edgejs",
        "nodejs",
        "meen"
    ],
    "author": "ducdhm@gmail.com",
    "license": "MIT",
    "bugs": {
        "url": "https://github.com/ducdhm/alimuaha-web/issues"
    },
    "homepage": "https://github.com/ducdhm/alimuaha-web#readme",
    "scripts": {
        "watch-admin": "webpack --progress --color --watch --config admin/static/webpack.config.js",
        "build-admin": "webpack --progress --color --prod --config admin/static/webpack.config.js",
        "start-admin": "nodemon --inspect admin/index.js",
        "start-api": "nodemon api/index.js",
        "watch-site": "webpack --progress --color --watch --config site/static/webpack.config.js",
        "build-site": "webpack --progress --color --prod --config site/static/webpack.config.js",
        "start-site": "nodemon --inspect site/index.js"
    },
    "nodemonConfig": {
        "ignore": [
            "public/**/*.js",
            "static/**/*.js",
            "tools/**/*.js",
            "webpack.config.js"
        ]
    },
    "devDependencies": {
        "@google-cloud/translate": "^6.0.0",
        "handlebars": "^4.7.6",
        "make-dir": "^3.1.0",
        "prettier": "2.0.5",
        "webpack": "^4.43.0",
        "webpack-cli": "^3.3.11"
    },
    "dependencies": {
        "@local/config": "file:@local/config",
        "@local/models": "file:@local/models",
        "@local/utils": "file:@local/utils",
        "@meenjs/core": "^1.9.1",
        "@meenjs/locale": "0.0.5",
        "@meenjs/static": "0.0.8",
        "@meenjs/utils": "^1.4.0",
        "bcryptjs": "^2.4.3",
        "chance": "^1.1.6",
        "connect-ensure-login": "^0.1.1",
        "edge.js": "^1.1.4",
        "jsonwebtoken": "^8.5.1",
        "moment": "^2.26.0",
        "mongoose": "^5.9.19",
        "mongoose-unique-validator": "^2.0.3",
        "nodemon": "^2.0.4",
        "passport": "^0.4.1",
        "passport-local": "^1.0.0"
    }
}
Quangs-MacBook-Pro:alimuaha-web quangdv$ cd ..
Quangs-MacBook-Pro:ExternalProject quangdv$ ls
ali-muaha-web		alimuaha-react
ali-muaha-web-api	alimuaha-web
Quangs-MacBook-Pro:ExternalProject quangdv$ rm -rf alimuaha-web/
Quangs-MacBook-Pro:ExternalProject quangdv$ git clone https://github.com/ducdhm/alimuaha-web.git
Cloning into 'alimuaha-web'...
Username for 'https://github.com': quangdv.90@gmail.com
Password for 'https://quangdv.90@gmail.com@github.com':
remote: Enumerating objects: 252, done.
remote: Counting objects: 100% (252/252), done.
remote: Compressing objects: 100% (161/161), done.
remote: Total 2344 (delta 120), reused 181 (delta 80), pack-reused 2092
Receiving objects: 100% (2344/2344), 26.86 MiB | 563.00 KiB/s, done.
Resolving deltas: 100% (1160/1160), done.
Quangs-MacBook-Pro:ExternalProject quangdv$ ls
ali-muaha-web		alimuaha-react
ali-muaha-web-api	alimuaha-web
Quangs-MacBook-Pro:ExternalProject quangdv$ cd alimuaha-web/
Quangs-MacBook-Pro:alimuaha-web quangdv$
Quangs-MacBook-Pro:alimuaha-web quangdv$
Quangs-MacBook-Pro:alimuaha-web quangdv$ ls
@local		admin		doc		public		tools
README.md	api		package.json	site
Quangs-MacBook-Pro:alimuaha-web quangdv$
Quangs-MacBook-Pro:alimuaha-web quangdv$
Quangs-MacBook-Pro:alimuaha-web quangdv$
Quangs-MacBook-Pro:alimuaha-web quangdv$
Quangs-MacBook-Pro:alimuaha-web quangdv$ npm i
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm ERR! Unexpected end of JSON input while parsing near '...0","linkinator":"^1.1'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/quangdv/.npm/_logs/2020-06-17T07_01_40_766Z-debug.log
Quangs-MacBook-Pro:alimuaha-web quangdv$ cat package.json
{
    "name": "alimuaha",
    "repository": {
        "type": "git",
        "url": "git+https://github.com/ducdhm/alimuaha-web.git"
    },
    "keywords": [
        "mongodb",
        "expressjs",
        "edgejs",
        "nodejs",
        "meen"
    ],
    "author": "ducdhm@gmail.com",
    "license": "MIT",
    "bugs": {
        "url": "https://github.com/ducdhm/alimuaha-web/issues"
    },
    "homepage": "https://github.com/ducdhm/alimuaha-web#readme",
    "scripts": {
        "watch-admin": "webpack --progress --color --watch --config admin/static/webpack.config.js",
        "build-admin": "webpack --progress --color --prod --config admin/static/webpack.config.js",
        "start-admin": "nodemon --inspect admin/index.js",
        "start-api": "nodemon api/index.js",
        "watch-site": "webpack --progress --color --watch --config site/static/webpack.config.js",
        "build-site": "webpack --progress --color --prod --config site/static/webpack.config.js",
        "start-site": "nodemon --inspect site/index.js"
    },
    "nodemonConfig": {
        "ignore": [
            "public/**/*.js",
            "static/**/*.js",
            "tools/**/*.js",
            "webpack.config.js"
        ]
    },
    "devDependencies": {
        "@google-cloud/translate": "^6.0.0",
        "handlebars": "^4.7.6",
        "make-dir": "^3.1.0",
        "prettier": "2.0.5",
        "webpack": "^4.43.0",
        "webpack-cli": "^3.3.11"
    },
    "dependencies": {
        "@local/config": "file:@local/config",
        "@local/models": "file:@local/models",
        "@local/utils": "file:@local/utils",
        "@meenjs/core": "^1.9.1",
        "@meenjs/locale": "0.0.5",
        "@meenjs/static": "0.0.8",
        "@meenjs/utils": "^1.4.0",
        "bcryptjs": "^2.4.3",
        "chance": "^1.1.6",
        "connect-ensure-login": "^0.1.1",
        "edge.js": "^1.1.4",
        "jsonwebtoken": "^8.5.1",
        "moment": "^2.26.0",
        "mongoose": "^5.9.19",
        "mongoose-unique-validator": "^2.0.3",
        "nodemon": "^2.0.4",
        "passport": "^0.4.1",
        "passport-local": "^1.0.0"
    }
}


I also tried deleting the node_modules and package lock but it seems the error still happening to me.

**Comment by quangdv90** [comment]
This my package.json
{
    "name": "alimuaha",
    "repository": {
        "type": "git",
        "url": "git+https://github.com/ducdhm/alimuaha-web.git"
    },
    "keywords": [
        "mongodb",
        "expressjs",
        "edgejs",
        "nodejs",
        "meen"
    ],
    "author": "ducdhm@gmail.com",
    "license": "MIT",
    "bugs": {
        "url": "https://github.com/ducdhm/alimuaha-web/issues"
    },
    "homepage": "https://github.com/ducdhm/alimuaha-web#readme",
    "scripts": {
        "watch-admin": "webpack --progress --color --watch --config admin/static/webpack.config.js",
        "build-admin": "webpack --progress --color --prod --config admin/static/webpack.config.js",
        "start-admin": "nodemon --inspect admin/index.js",
        "start-api": "nodemon api/index.js",
        "watch-site": "webpack --progress --color --watch --config site/static/webpack.config.js",
        "build-site": "webpack --progress --color --prod --config site/static/webpack.config.js",
        "start-site": "nodemon --inspect site/index.js"
    },
    "nodemonConfig": {
        "ignore": [
            "public/**/*.js",
            "static/**/*.js",
            "tools/**/*.js",
            "webpack.config.js"
        ]
    },
    "devDependencies": {
        "@google-cloud/translate": "^6.0.0",
        "handlebars": "^4.7.6",
        "make-dir": "^3.1.0",
        "prettier": "2.0.5",
        "webpack": "^4.43.0",
        "webpack-cli": "^3.3.11"
    },
    "dependencies": {
        "@local/config": "file:@local/config",
        "@local/models": "file:@local/models",
        "@local/utils": "file:@local/utils",
        "@meenjs/core": "^1.9.1",
        "@meenjs/locale": "0.0.5",
        "@meenjs/static": "0.0.8",
        "@meenjs/utils": "^1.4.0",
        "bcryptjs": "^2.4.3",
        "chance": "^1.1.6",
        "connect-ensure-login": "^0.1.1",
        "edge.js": "^1.1.4",
        "jsonwebtoken": "^8.5.1",
        "moment": "^2.26.0",
        "mongoose": "^5.9.19",
        "mongoose-unique-validator": "^2.0.3",
        "nodemon": "^2.0.4",
        "passport": "^0.4.1",
        "passport-local": "^1.0.0"
    }
}


I also tried deleting the node_modules and package lock but it seems the error still happening to me.

**Comment by JustinBeckwith** [comment]
Greetings!  I'm having a little trouble reproducing this one.  On OSX, with the same version of node, this works on my machine:

```js
$ node -v
v12.18.0

$ npm install @google-cloud/translate

> protobufjs@6.10.0 postinstall /Users/beckwith/Code/ttt/node_modules/protobufjs
> node scripts/postinstall

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN ttt@1.0.0 No description
npm WARN ttt@1.0.0 No repository field.

+ @google-cloud/translate@6.0.1
added 82 packages from 92 contributors and audited 82 packages in 6.48s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

I have to think there's something very specific to your config that's causing issues.  Could I trouble you to try the following, and share the exact output?  

```
node -v
npm -v
mkdir testy
cd testy
npm init -y 
npm install @google-cloud/translate
cat package.json
```
