### ISSUE TITLE
INVALID_ARGUMENT: Text is too long

### ISSUE THREAD

**Issue by fkirc** [googleapis/nodejs-translate#588]
I am not sure whether this is a bug; perhaps I am just missing some documentation.

I have a "large" string-array with about 300 medium-sized sentences.
I tried to translate this array via a single call to `client.translateText`, but I get the following error:

> 3 INVALID_ARGUMENT: Text is too long.
> Error: 3 INVALID_ARGUMENT: Text is too long.
>     at Object.callErrorFromStatus (/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
>     at Object.onReceiveStatus (/node_modules/@grpc/grpc-js/build/src/client.js:176:52)
>     at Object.onReceiveStatus (/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:342:141)
>     at Object.onReceiveStatus (/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:305:181)
>     at /node_modules/@grpc/grpc-js/build/src/call-stream.js:124:78

To fix this, I might change my code into multiple, smaller calls to `client.translateText`.
However, I would like to know if there are any clearly-defined size-limits.
After all, it might be really slow to translate each text individually.

My code looks like this:

```TypeScript
import { google } from "@google-cloud/translate/build/protos/protos";
import ITranslateTextRequest = google.cloud.translation.v3.ITranslateTextRequest;
import { ClientOptions } from "google-gax";
import ITranslation = google.cloud.translation.v3.ITranslatio
import { TranslationServiceClient } from "@google-cloud/translate";

const request: ITranslateTextRequest = {
      parent: `projects/${projectId}/locations/${location}`,
      contents: stringsToTranslate, // "Large" array with about 300 sentences!
      mimeType: "text/plain",
      sourceLanguageCode: args.srcLng,
      targetLanguageCode: args.targetLng,
};
const [response] = await client.translateText(request);
```

### Environment details

  - OS: macOS 10.15.6
  - Node.js version: v14.13.0
  - npm version: 6.14.8
  - `@google-cloud/translate` version: 6.0.3

**Comment by stephenplusplus** [comment]
Quotas and limits are talked about here: https://cloud.google.com/translate/quotas

> The Cloud Translation API is optimized for translating of smaller requests. The recommended maximum length for each request is 5K characters. However, the more characters that you include, the higher the response latency. For Cloud Translation - Advanced, the maximum number of code points for a single request is 30K. Cloud Translation - Basic has a maximum request size of 100K bytes.
>
> The Cloud Translation API rejects requests larger than the maximum and gives a 400 INVALID_ARGUMENT error regardless of the available quota.
