### ISSUE TITLE
Fatal error: committing semi space failed. Allocation failed - process out of memory

### ISSUE THREAD

**Issue by manojn-arkenea** [googleapis/nodejs-translate#600]
Hello,

translate work fine for less records but when we trying to translate large data then we are getting error 
"Fatal error: committing semi space failed. Allocation failed - process out of memory"

**Comment by manojn-arkenea** [comment]
FATAL ERROR: Scavenger: semi-space copy

**Comment by munkhuushmgl** [comment]
Have u tried increasing the default limit of memory usage by manual?

**Comment by munkhuushmgl** [comment]
Due to inactivity, I am closing this issue. Feel free to reopen this issue.
