### ISSUE TITLE
TS definition for google-auth-library is missing BaseExternalAccountClient

### ISSUE THREAD

**Issue by lahdekorpi** [googleapis/nodejs-translate#653]
#### Environment details

  - OS: Ubuntu 21.04
  - Node.js version: 15
  - npm version: 7.8.0
  - `@google-cloud/translate` version: 6.2.0
  - TypeScript version: 4.2.4

#### Steps to reproduce

  1. Install and import translate
  2. Try to compile with TypeScript

```
node_modules/google-gax/build/src/fallback.d.ts:21:69 - error TS2305: Module '"google-auth-library"' has no exported member 'BaseExternalAccountClient'.
21 import { GoogleAuth, OAuth2Client, Compute, JWT, UserRefreshClient, BaseExternalAccountClient } from 'google-auth-library';
```

**Comment by munkhuushmgl** [comment]
Hey @lahdekorpi ,

Could you re-install node packages?
1. delete `package-lock.json`
2. install packages again
```
npm install 
```

If the problem persists, please let me know.

**Comment by lahdekorpi** [comment]
That worked. For some reason, npm had two versions of google-auth-library even after updating the packages.
