### ISSUE TITLE
ENOENT: no such file or directory, open 'operations.json' 

### ISSUE THREAD

**Issue by dmarczydlo** [googleapis/nodejs-translate#663]
The new version of nodejs-translate resolve the problem with `ENOENT: no such file or directory, open '/protos/protos.json` requested https://github.com/googleapis/nodejs-pubsub/issues/1246 but right now there is a new problem 

`ENOENT: no such file or directory, open 'operations.json'`

Information about my environment:
`"@google-cloud/translate": "^6.2.1"` used as dependencies on Lambda (AWS)

Version of node : `Node.js 10.x`

Application has been written in TypeScript. 

Full output of stack:

`"stack": "Error: ENOENT: no such file or directory, open 'operations.json'\n    at Object.openSync (fs.js:443:3)\n    at Object.readFileSync (fs.js:343:35)\n    at fetch (/var/task/app.js:99576:34)\n    at Root.load (/var/task/app.js:99610:13)\n    at Root.loadSync (/var/task/app.js:99651:17)\n    at Object.loadProtosWithOptionsSync (/var/task/app.js:199897:29)\n    at Object.loadSync (/var/task/app.js:195232:31)\n    at GrpcClient.loadFromProto (/var/task/app.js:97086:48)\n    at GrpcClient.loadProto (/var/task/app.js:97117:21)\n    at new OperationsClientBuilder (/var/task/app.js:100198:40)"`

**Comment by alexander-fenster** [comment]
@dmarczydlo Yes, apparently this is one more place where the proto JSON was loaded. I fixed it in google-gax v2.13.0, please update your `node_modules` (make sure to delete `package-lock.json` as well) to pull the latest one (`npm ls google-gax` should say 2.13.0).
