### ISSUE TITLE
URGENT - Google Translation APIs started to give our web app on Firebase the strange problem/bug from July 23, 2021

### ISSUE THREAD

**Issue by eGlobeBizCom** [googleapis/nodejs-translate#706]
Hi All

*Our Firebase Functions web apps connected with Google Translation API had worked correctly from 2017 till July 22/2021; 

* We had not touched the code package of our apps before July23, 2021;  Then from July 23, we  found out that our apps gave this error:  The foreign language input on our apps get no info from Google Translation API; 
* 

*We found the following  Error Message inside Firebase Functions Dashboard in our apps caused the above issue; 
```
================
Accessing deprecated metadata server endpoint at "/computeMetadata/v1beta1/instance/service-accounts/default/token" from user-agent "google-api-nodejs-client/0.10.0" 
====================
```

*After lots of searches over the web including the following forums, very few posts related to the above Error Message are found, very STRANGE!   We have done lots of work to solve this issue, but we have not found any solution for the above issue;
```
============
    - Search the issues already opened: https://github.com/googleapis/nodejs-translate/issues
  - Search the issues on our "catch-all" repository: https://github.com/googleapis/google-cloud-node
  - Search or ask on StackOverflow (engineers monitor these tags): http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js
=============
```

Any suggestions and help will be highly appreciated for the above urgent Error Message!  Lots of thanks in advance!!

**Comment by JustinBeckwith** [comment]
Greetings!  If you're getting that error, it likely means you have some very, very old dependencies in your tree.  What version of `@google-cloud/translate` do you have in `package.json`?  Do you specifically have a version of `google-auth-library` installed?  (You probably don't want that installed separately).

**Comment by JustinBeckwith** [comment]
Actually taking a closer look - can you confirm if you're using `googleapis` or `@google-cloud/translate`?  These are very different packages.

**Comment by eGlobeBizCom** [comment]
Hi Justine, 

Thank you very much for your fast reply!

# In our Index.js on Firebase Function app, we used the following code and had worked since 2020

```
=============
   const Translate = require('@google-cloud/translate');

//initialize user input variables, later on will be replaced/updated by the url request's param.
var userinp = 'init';
var app = express();
============
```

# Do we still need to reply the Q in your previous post:
=================
What version of @google-cloud/translate do you have in package.json? Do you specifically have a version of google-auth-library installed? (You probably don't want that installed separately).
=================

Thanks!

**Comment by eGlobeBizCom** [comment]
### Subject: We updated Google Translation version in Package.json today, but our app still cannot talk with Google Translation API and Firebase Functions still gave this Error Message   (TypeError: Translate is not a constructor)


Hi All,

We tried to update  our code package with the latest Firebase libraries. The results of this update: Index.js file in our Node app stopped talking with Dialogflow API, so this app code package is only updated with Dec/2020 Firebase libraries.   Based on your suggestions, we experimented the following to fix this issue:

*We Updated this line of code in this file:  package.json
```
============
"@google-cloud/translate": "^6.2.6",
=============
```
The code package is deployed successfully;


*The testing results of the above update: This app still cannot talk with Google Translation APIs;

*The Firebase Cloud Functions Dashboard gave the following Error Message:
```
_==================
      6:03:32.612 PM
app   Function execution started 

6:03:32.616 PM
app   userinp: 帮助
	
6:03:32.616 PM
app  { term: '帮助 ', langs: 'en' }
(My note: Our app user's input "帮助"  to be translated into English through Google Translation API)

6:03:32.619 PM
app     Function execution took 8 ms, finished with status code: 500
	
6:03:32.620 PM
app   TypeError: Translate is not a constructor
	
6:03:32.620 PM	
app    at /workspace/index.js:172:20
	
6:03:32.620 PM
app    at Layer.handle [as handle_request] (/workspace/node_modules/express/lib/router/layer.js:95:5)
================_
```

Welcome any suggestions and feedback for the above error!

**Comment by JustinBeckwith** [comment]
There were some breaking changes from older versions to the newest versions.  You probably need to destructure the assignment, as we call out in the README:

```js
// Imports the Google Cloud client library
const {Translate} = require('@google-cloud/translate').v2;

// Instantiates a client
const translate = new Translate({projectId});
```

**Comment by eGlobeBizCom** [comment]
**Subject:  Your suggestion helped fix this issue in our Index.js file + Why were we not REPTEATEDLY informed about the latest changes in Google Cloud Translation API?**

Hi Justin,

Thank you very much for your timely suggestions, that helped me fix this issue. 

*I updated the latest Google Translation API to the latest version in Package.json; 

*Run the following code in Firebase Deployment Console:
============
npm install @google-cloud/translate
===============
 
*I used the following code to replace the old code in our Index.js:
==============
      const projectId = 'The Firebase ProjectID';
     const {Translate} = require('@google-cloud/translate').v2;
    // Instantiates a client
     const translate = new Translate({projectId});
=============
Hope the above is helpful to this community;

# I am wondering about this:  Why were we not informed about the latest changes in Google Cloud Translation API?


Thanks,
H.
