### ISSUE TITLE
Library does not suport europe region

### ISSUE THREAD

**Issue by Mistic92** [googleapis/nodejs-translate#791]
#### Environment details

  - OS: Win 11 + wsl2
  - Node.js version: 18
  - npm version: 8
  - `@google-cloud/translate` version: 6.3.1

#### Steps to reproduce

  1. Create request with location set to europe-west1
  2. Try to do request

```
import { TranslationServiceClient } from '@google-cloud/translate';
....
...
  async translate(text: string, sourceLang: string, targetLang = "en"): Promise<string> {
    const request = {
      parent: `projects/${process.env["GCLOUD_PROJECT"]}/locations/europe-west1`,
      contents: [text],
      mimeType: "text/plain",
      sourceLanguageCode: sourceLang,
      targetLanguageCode: targetLang,
    };

    // Run request
    const [response] = await this.gTranslate.translateText(request);
    return response.translations[0]?.translatedText || "";
  }
  ```
  
  I'm getting error
  ```
  Error: 3 INVALID_ARGUMENT: Invalid 'parent'.; Invalid location name. Unsupported location 'europe-west1'. Must be 'us-central1' or 'global'.
  ```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by mattcarrolldev** [comment]
As indicated by the error message and the translate APIs `projects.locations.list` method the API is only supported in the `us-central1` and `global` regions. If you're calling the API from Europe I'd recommend the `global` region.

You can call the `projects.locations.list` API yourself via the API explorer on this page to verify what regions the API is available in for yourself: https://cloud.google.com/translate/docs/reference/rest/v3/projects.locations/list
